"""PromptRenderer — full prompt rendering for baton musicians.

Bridges the PromptBuilder pipeline with the baton's Sheet-based execution
model. Replaces the bare-bones ``_build_prompt()`` in ``musician.py`` with
the full 9-layer prompt assembly:

    1. Preamble (positional identity)
    2. Template rendering (Jinja2 with all variables)
    3. Skills/tools injection (prelude/cadenza with category=skill/tool)
    4. Context injection (prelude/cadenza with category=context)
    5. Spec fragments (from specification corpus)
    6. Failure history (from previous sheets)
    7. Learned patterns (from learning store)
    8. Validation requirements (as agent-readable checklist)
    9. Completion suffix (for completion mode retries)

The renderer is intentionally stateless — create one per job, call
``render()`` per sheet. No runner dependency, no mixin inheritance.

This is the F-104 fix. Without it, the baton produces raw
templates instead of rendered prompts.

See: ``docs/plans/2026-03-26-baton-design.md`` — Prompt Assembly
"""

from __future__ import annotations

import hashlib
import os
import re
import tempfile
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, ClassVar

import jinja2
import yaml

from marianne.core.config.job import InjectionCategory, InjectionItem, PromptConfig
from marianne.core.sheet import Sheet
from marianne.daemon.baton.state import AttemptContext
from marianne.prompts.preamble import build_preamble
from marianne.prompts.templating import PromptBuilder, SheetContext

if TYPE_CHECKING:
    from marianne.core.config.spec import SpecFragment
    from marianne.execution.validation import HistoricalFailure

from marianne.core.logging import get_logger

_logger = get_logger("daemon.baton.prompt")


@dataclass(frozen=True)
class RenderedPrompt:
    """Output of the prompt rendering pipeline.

    Contains both the rendered prompt (for backend execution) and the
    preamble (set on the backend before execution). Separating them
    allows the musician to configure the backend correctly.
    """

    prompt: str
    """Fully rendered prompt with all injections and context layers."""

    preamble: str
    """Dynamic preamble with positional identity and retry status."""

    context_manifest: tuple[dict[str, object], ...] = ()
    """Hash-only manifest of context and technique bytes in ``prompt``."""


class PromptRenderer:
    """Renders full prompts for baton musicians.

    Bridges the PromptBuilder pipeline with the baton's Sheet-based
    execution model. Handles template rendering, injection resolution,
    preamble assembly, and validation requirements — everything the
    old runner's context mixin did, but without the runner dependency.

    Create one per job (or share across jobs with the same config).
    Call ``render()`` per sheet dispatch.

    Args:
        prompt_config: The job's PromptConfig (template, variables, etc.).
        total_sheets: Total sheets in the job (for preamble).
        total_stages: Total stages before fan-out expansion (for template aliases).
        parallel_enabled: Whether parallel execution is enabled (for preamble).
    """

    def __init__(
        self,
        prompt_config: PromptConfig,
        total_sheets: int,
        total_stages: int,
        parallel_enabled: bool,
    ) -> None:
        self._prompt_config = prompt_config
        self._total_sheets = total_sheets
        self._total_stages = total_stages
        self._parallel_enabled = parallel_enabled

    def render(
        self,
        sheet: Sheet,
        attempt_context: AttemptContext,
        *,
        patterns: list[str] | None = None,
        failure_history: list[HistoricalFailure] | None = None,
        spec_fragments: list[SpecFragment] | None = None,
        technique_manifest: str | None = None,
        technique_skill_docs: Mapping[str, str] | Sequence[str] | None = None,
        raw_prompt: bool = False,
    ) -> RenderedPrompt:
        """Render a full prompt for a sheet execution.

        Performs the complete 9-layer prompt assembly:
        template rendering -> injection resolution -> optional layers ->
        validation requirements -> completion suffix.

        Args:
            sheet: The Sheet entity to render for.
            attempt_context: Context from the baton (attempt number, mode).
            patterns: Optional learned pattern descriptions to inject.
            failure_history: Optional historical failures from previous sheets.
            spec_fragments: Optional spec corpus fragments to inject.
            technique_manifest: Optional technique manifest text to inject
                as a skill-category item. Generated by the technique resolver
                from the job's technique declarations filtered by phase.
            technique_skill_docs: Optional list of technique document contents
                discovered by the technique resolver. Each entry is the full
                text of a skill-kind technique document, injected as a
                skill-category item alongside the manifest.
            raw_prompt: When True (driven by the instrument profile's
                ``raw_prompt`` field), verify required attachments but do not
                deliver their bytes, then skip technique injection, completion
                suffix, and the preamble. The resulting RenderedPrompt carries
                the rendered Jinja template only, with an empty preamble. Used
                for instruments like the bash ``cli`` profile whose input must
                remain a literal command.

        Returns:
            RenderedPrompt with fully rendered prompt and preamble.
        """
        # Layer 1: Build SheetContext from Sheet entity (F-210: includes cross-sheet)
        context = self._build_context(sheet, attempt_context)

        # Layer 2-3: Resolve prelude/cadenza injections into the context.  Raw
        # command profiles do not receive these bytes, but ``required`` still
        # means required: resolve first so a missing/invalid attachment fails
        # closed instead of being silently bypassed.
        self._resolve_injections(context, sheet)

        if not raw_prompt:
            # Layer 2.5: Inject technique manifest and skill documents.
            # Skill docs go FIRST (they're the actual knowledge the musician
            # needs), then the manifest (lists what's available). Both are
            # injected as skill-category items so they appear before the
            # template in the assembled prompt.
            if technique_skill_docs:
                named_docs = (
                    technique_skill_docs.items()
                    if isinstance(technique_skill_docs, Mapping)
                    else (
                        (f"document-{index}", doc)
                        for index, doc in enumerate(technique_skill_docs, 1)
                    )
                )
                for name, doc in named_docs:
                    context.injected_skills.append(doc)
                    self._record_delivery(
                        context,
                        source=f"technique:{name}",
                        category=InjectionCategory.SKILL,
                        delivered_content=doc,
                        delivery_kind="inline-technique",
                    )
            if technique_manifest and not self._template_contains_technique_manifest(
                sheet
            ):
                context.injected_skills.append(technique_manifest)
                self._record_delivery(
                    context,
                    source="technique-manifest",
                    category=InjectionCategory.SKILL,
                    delivered_content=technique_manifest,
                    delivery_kind="inline-technique-manifest",
                )

        # Layer 4-8: Build prompt through PromptBuilder (raw_prompt short-circuits inside)
        prompt = self._build_prompt(
            sheet, context, patterns, failure_history, spec_fragments,
            raw_prompt=raw_prompt,
        )

        if raw_prompt:
            # No completion suffix, no preamble — the instrument receives
            # the rendered template verbatim. Empty preamble is the
            # "no preamble" sentinel.
            return RenderedPrompt(prompt=prompt, preamble="", context_manifest=())

        # Layer 9: Completion mode suffix
        if attempt_context.completion_prompt_suffix:
            prompt = f"{prompt}\n\n{attempt_context.completion_prompt_suffix}"

        # Preamble: positional identity + retry status
        retry_count = max(0, attempt_context.attempt_number - 1)
        preamble = build_preamble(
            sheet_num=sheet.num,
            total_sheets=self._total_sheets,
            workspace=sheet.workspace,
            retry_count=retry_count,
            is_parallel=self._parallel_enabled,
            healing_context=attempt_context.healing_context,
        )

        return RenderedPrompt(
            prompt=prompt,
            preamble=preamble,
            context_manifest=tuple(context.delivery_manifest),
        )

    def _build_context(
        self,
        sheet: Sheet,
        attempt_context: AttemptContext | None = None,
    ) -> SheetContext:
        """Build SheetContext from a Sheet entity.

        Populates fan-out metadata (movement/voice) from the Sheet's
        own fields rather than querying config.sheet.get_fan_out_metadata().
        The Sheet already has these values resolved by build_sheets().

        F-210: When attempt_context is provided, populates cross-sheet
        context (previous_outputs and previous_files) from the context.
        This bridges the baton's AttemptContext to the template's
        SheetContext, enabling {{ previous_outputs }} and {{ previous_files }}
        in templates.

        Args:
            sheet: The Sheet entity.
            attempt_context: Optional attempt context with cross-sheet data.

        Returns:
            SheetContext with identity, workspace, fan-out, and cross-sheet metadata.
        """
        # Item range defaults: for non-batch scores, start == end == sheet_num
        start_item = sheet.num
        end_item = sheet.num

        context = SheetContext(
            sheet_num=sheet.num,
            total_sheets=self._total_sheets,
            start_item=start_item,
            end_item=end_item,
            workspace=sheet.workspace,
            instrument_name=sheet.instrument_name,
        )

        # Fan-out metadata from the Sheet entity
        context.stage = sheet.movement if sheet.movement else sheet.num
        context.instance = sheet.voice if sheet.voice else 1
        context.fan_count = sheet.voice_count
        context.total_stages = (
            self._total_stages if self._total_stages > 0 else self._total_sheets
        )

        # F-210: Cross-sheet context from AttemptContext
        if attempt_context is not None:
            context.previous_outputs = dict(attempt_context.previous_outputs)
            context.previous_files = dict(attempt_context.previous_files)

        return context

    @staticmethod
    def _template_contains_technique_manifest(sheet: Sheet) -> bool:
        """Return true when the sheet template already lists active techniques.

        Compiler-generated scores embed a phase-specific manifest in the
        prompt template, while the runtime still resolves skill documents and
        MCP/A2A support at dispatch. Suppress only the redundant runtime
        manifest so live prompts do not list the same technique surface twice.
        """
        template_text = sheet.prompt_template
        if not template_text and sheet.template_file and sheet.template_file.exists():
            try:
                template_text = sheet.template_file.read_text(encoding="utf-8")
            except OSError:
                template_text = None
        if not template_text:
            return False
        return "Techniques Available" in template_text

    # Binary file extensions and their human-readable descriptions
    _BINARY_EXTENSIONS: ClassVar[dict[str, str]] = {
        ".pdf": "PDF document",
        ".png": "image",
        ".jpg": "image",
        ".jpeg": "image",
        ".gif": "image",
        ".webp": "image",
        ".docx": "Word document",
        ".xlsx": "spreadsheet",
        ".xls": "spreadsheet",
    }

    def _resolve_injections(
        self,
        context: SheetContext,
        sheet: Sheet,
    ) -> None:
        """Resolve prelude and cadenza injections from the Sheet entity.

        Reads files referenced by InjectionItems, expands Jinja2 templates
        in file/directory paths, and populates the SheetContext injection fields.

        Supports two injection modes:
        - ``file``: inject a single file's content
        - ``directory`` (directory cadenza): glob all files in a directory,
          inject text files inline, inject binary files as structured read
          instructions with absolute paths.

        Missing context files are skipped with a warning. Missing skill/tool
        files log an error but don't raise (the musician should still execute).

        Args:
            context: SheetContext to populate with injection content.
            sheet: Sheet entity with prelude/cadenza items.
        """
        items: list[tuple[str, InjectionItem]] = [
            *(("prelude", item) for item in sheet.prelude),
            *(("cadenza", item) for item in sheet.cadenza),
        ]
        if not items:
            return

        # Template variables for Jinja path expansion
        template_vars = context.to_dict()
        template_vars.update(sheet.variables)

        env = jinja2.Environment(
            undefined=jinja2.StrictUndefined,
            autoescape=False,
        )

        for source, item in items:
            if item.directory is not None:
                self._resolve_directory_cadenza(
                    item,
                    context,
                    sheet,
                    env,
                    template_vars,
                    source=source,
                )
            else:
                self._resolve_file_injection(
                    item,
                    context,
                    sheet,
                    env,
                    template_vars,
                    source=source,
                )

    def _resolve_directory_cadenza(
        self,
        item: InjectionItem,
        context: SheetContext,
        sheet: Sheet,
        env: jinja2.Environment,
        template_vars: dict[str, object],
        *,
        source: str,
    ) -> None:
        """Resolve a directory cadenza injection."""
        assert item.directory is not None  # guaranteed by caller
        try:
            tmpl = env.from_string(item.directory)
            expanded_path = tmpl.render(**template_vars)
        except jinja2.TemplateError as e:
            if item.required:
                raise ValueError(
                    f"required injection directory template is invalid: {item.directory}"
                ) from e
            _logger.warning(
                "prompt_renderer.path_expansion_error",
                extra={"directory": item.directory, "error": str(e)},
            )
            return

        if not expanded_path.strip():
            if item.required:
                raise ValueError("required injection directory resolved to an empty path")
            return

        dir_path = resolve_injection_path(expanded_path, sheet.workspace)

        if not dir_path.is_dir():
            if item.required:
                raise FileNotFoundError(
                    f"required injection directory not found: {dir_path}"
                )
            if item.as_ == InjectionCategory.CONTEXT:
                _logger.info(
                    "prompt_renderer.directory_not_found",
                    extra={"directory": str(dir_path), "category": item.as_.value},
                )
            else:
                _logger.error(
                    "prompt_renderer.required_directory_not_found",
                    extra={"directory": str(dir_path), "category": item.as_.value},
                )
            return

        files = sorted(f for f in dir_path.glob("*") if f.is_file())
        if not files:
            if item.required:
                raise FileNotFoundError(
                    f"required injection directory is empty: {dir_path}"
                )
            _logger.info(
                "prompt_renderer.directory_empty",
                extra={"directory": str(dir_path)},
            )
            return

        for file_path in files:
            self._inject_single_file(
                item,
                context,
                file_path,
                from_directory=True,
                source=source,
                declared_path=item.directory,
            )

    def _resolve_file_injection(
        self,
        item: InjectionItem,
        context: SheetContext,
        sheet: Sheet,
        env: jinja2.Environment,
        template_vars: dict[str, object],
        *,
        source: str,
    ) -> None:
        """Resolve a single-file injection."""
        assert item.file is not None  # guaranteed by caller
        try:
            tmpl = env.from_string(item.file)
            expanded_path = tmpl.render(**template_vars)
        except jinja2.TemplateError as e:
            if item.required:
                raise ValueError(
                    f"required injection file template is invalid: {item.file}"
                ) from e
            _logger.warning(
                "prompt_renderer.path_expansion_error",
                extra={"file": item.file, "error": str(e)},
            )
            return

        if not expanded_path.strip():
            if item.required:
                raise ValueError("required injection file resolved to an empty path")
            return

        path = resolve_injection_path(expanded_path, sheet.workspace)

        if not path.is_file():
            if item.required:
                raise FileNotFoundError(f"required injection file not found: {path}")
            if item.as_ == InjectionCategory.CONTEXT:
                _logger.warning(
                    "prompt_renderer.file_not_found",
                    extra={"file": str(path), "category": item.as_.value},
                )
            else:
                _logger.error(
                    "prompt_renderer.file_not_found",
                    extra={"file": str(path), "category": item.as_.value},
                )
            return

        self._inject_single_file(
            item,
            context,
            path,
            source=source,
            declared_path=item.file,
        )

    def _inject_single_file(
        self,
        item: InjectionItem,
        context: SheetContext,
        path: Path,
        *,
        from_directory: bool = False,
        source: str,
        declared_path: str | None,
    ) -> None:
        """Inject a single file, classifying as text or binary."""
        try:
            content = path.read_text(encoding="utf-8")
            if from_directory:
                header = f"--- Input: {path.name} ---\n\n"
                full_content = header + content
            else:
                full_content = content
        except UnicodeDecodeError:
            ext = path.suffix.lower()
            file_kind = self._BINARY_EXTENSIONS.get(ext, "file")
            full_content = (
                f"--- Input: {path.name} (binary — {file_kind}, read with your tools) ---\n\n"
                f"This file cannot be displayed inline. Read it using your file reading tools.\n"
                f"Path: {path.resolve()}\n"
            )
        except OSError as e:
            if item.required:
                raise OSError(f"required injection could not be read: {path}") from e
            _logger.warning(
                "prompt_renderer.file_read_error",
                extra={"file": str(path), "error": str(e)},
            )
            return

        if item.as_ == InjectionCategory.CONTEXT:
            context.injected_context.append(full_content)
        elif item.as_ == InjectionCategory.SKILL:
            context.injected_skills.append(full_content)
        elif item.as_ == InjectionCategory.TOOL:
            context.injected_tools.append(full_content)

        try:
            source_bytes = path.read_bytes()
        except OSError as exc:
            if item.required:
                raise OSError(f"required injection could not be hashed: {path}") from exc
            source_bytes = None
        self._record_delivery(
            context,
            source=source,
            category=item.as_,
            delivered_content=full_content,
            resolved_path=path,
            declared_path=declared_path,
            source_bytes=source_bytes,
            delivery_kind="directory-inline" if from_directory else "file-inline",
        )

    @staticmethod
    def _record_delivery(
        context: SheetContext,
        *,
        source: str,
        category: InjectionCategory,
        delivered_content: str,
        delivery_kind: str,
        resolved_path: Path | None = None,
        declared_path: str | None = None,
        source_bytes: bytes | None = None,
    ) -> None:
        """Record provenance without copying private context into the receipt."""
        delivered_bytes = delivered_content.encode("utf-8")
        entry: dict[str, object] = {
            "source": source,
            "category": category.value,
            "delivery_kind": delivery_kind,
            "delivered_sha256": _sha256(delivered_bytes),
            "delivered_bytes": len(delivered_bytes),
        }
        if declared_path is not None:
            entry["declared_path"] = declared_path
        if resolved_path is not None:
            entry["resolved_path"] = str(resolved_path.resolve())
        if source_bytes is not None:
            entry["source_sha256"] = _sha256(source_bytes)
            entry["source_bytes"] = len(source_bytes)
        context.delivery_manifest.append(entry)

    def _build_prompt(
        self,
        sheet: Sheet,
        context: SheetContext,
        patterns: list[str] | None,
        failure_history: list[HistoricalFailure] | None,
        spec_fragments: list[SpecFragment] | None,
        *,
        raw_prompt: bool = False,
    ) -> str:
        """Build the rendered prompt through PromptBuilder.

        Creates a per-sheet PromptConfig with the sheet's template and
        merged variables, then delegates to PromptBuilder.build_sheet_prompt()
        for the full rendering pipeline.

        Args:
            sheet: Sheet entity with template and variables.
            context: Populated SheetContext with injections.
            patterns: Optional learned patterns.
            failure_history: Optional failure history.
            spec_fragments: Optional spec corpus fragments.

        Returns:
            Fully rendered prompt string.
        """
        # Merge global config variables with sheet-specific variables
        merged_vars = dict(self._prompt_config.variables)
        merged_vars.update(sheet.variables)

        # Determine template: sheet.prompt_template or sheet.template_file
        template_text = sheet.prompt_template
        template_file = sheet.template_file

        # Load template file if no inline template
        if not template_text and template_file and template_file.exists():
            template_text = template_file.read_text(encoding="utf-8")

        sheet_prompt_config = self._prompt_config.model_copy(
            update={
                "template": template_text,
                "template_file": None,  # Already loaded above
                "variables": merged_vars,
            }
        )

        builder = PromptBuilder(sheet_prompt_config)

        return builder.build_sheet_prompt(
            context,
            patterns=patterns if patterns else None,
            validation_rules=sheet.validations if sheet.validations else None,
            failure_history=failure_history if failure_history else None,
            spec_fragments=spec_fragments if spec_fragments else None,
            raw_prompt=raw_prompt,
        )


def write_context_delivery_receipt(
    *,
    workspace: Path,
    job_id: str,
    sheet_num: int,
    attempt: int,
    instrument: str,
    rendered: RenderedPrompt,
) -> Path:
    """Persist proof of the exact prompt context passed to ``sheet_task``."""
    safe_job = re.sub(r"[^A-Za-z0-9._-]+", "-", job_id).strip("-._") or "job"
    safe_job = f"{safe_job}-{hashlib.sha256(job_id.encode()).hexdigest()[:10]}"
    receipt_dir = workspace / ".marianne" / "context-receipts" / safe_job
    receipt_path = receipt_dir / f"sheet-{sheet_num:04d}-attempt-{attempt:03d}.yaml"
    document: dict[str, object] = {
        "schema_version": 1,
        "kind": "marianne-context-delivery-receipt",
        "status": "delivered_to_sheet_task",
        "delivery_boundary": "rendered prompt argument passed to sheet_task",
        "job_id": job_id,
        "sheet_num": sheet_num,
        "attempt": attempt,
        "instrument": instrument,
        "prompt_sha256": _sha256(rendered.prompt.encode("utf-8")),
        "preamble_sha256": _sha256(rendered.preamble.encode("utf-8")),
        "context_manifest": list(rendered.context_manifest),
    }
    _atomic_write_yaml(receipt_path, document)
    return receipt_path


def resolve_injection_path(expanded_path: str, workspace: Path) -> Path:
    """Resolve one rendered injection path with portable HOME semantics."""
    path = Path(expanded_path).expanduser()
    return path if path.is_absolute() else workspace / path


def _sha256(value: bytes) -> str:
    return f"sha256:{hashlib.sha256(value).hexdigest()}"


def _atomic_write_yaml(path: Path, document: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, raw_temp = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temp_path = Path(raw_temp)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            yaml.safe_dump(document, handle, sort_keys=False, allow_unicode=True)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_path, path)
    finally:
        if temp_path.exists():
            temp_path.unlink()
